/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as MarketRouteImport } from './routes/market'
import { Route as RelativesRouteImport } from './routes/relatives'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as SoulmatesRouteImport } from './routes/soulmates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const RelativesRoute = RelativesRouteImport.update({
  id: '/relatives',
  path: '/relatives',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulmatesRoute = SoulmatesRouteImport.update({
  id: '/soulmates',
  path: '/soulmates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/market': typeof MarketRoute
  '/relatives': typeof RelativesRoute
  '/rooms': typeof RoomsRoute
  '/scores': typeof ScoresRoute
  '/soulmates': typeof SoulmatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/market': typeof MarketRoute
  '/relatives': typeof RelativesRoute
  '/rooms': typeof RoomsRoute
  '/scores': typeof ScoresRoute
  '/soulmates': typeof SoulmatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/market': typeof MarketRoute
  '/relatives': typeof RelativesRoute
  '/rooms': typeof RoomsRoute
  '/scores': typeof ScoresRoute
  '/soulmates': typeof SoulmatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chats'
    | '/market'
    | '/relatives'
    | '/rooms'
    | '/scores'
    | '/soulmates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chats'
    | '/market'
    | '/relatives'
    | '/rooms'
    | '/scores'
    | '/soulmates'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chats'
    | '/market'
    | '/relatives'
    | '/rooms'
    | '/scores'
    | '/soulmates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  MarketRoute: typeof MarketRoute
  RelativesRoute: typeof RelativesRoute
  RoomsRoute: typeof RoomsRoute
  ScoresRoute: typeof ScoresRoute
  SoulmatesRoute: typeof SoulmatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatives': {
      id: '/relatives'
      path: '/relatives'
      fullPath: '/relatives'
      preLoaderRoute: typeof RelativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soulmates': {
      id: '/soulmates'
      path: '/soulmates'
      fullPath: '/soulmates'
      preLoaderRoute: typeof SoulmatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  MarketRoute: MarketRoute,
  RelativesRoute: RelativesRoute,
  RoomsRoute: RoomsRoute,
  ScoresRoute: ScoresRoute,
  SoulmatesRoute: SoulmatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
